### PR TITLE
Updates to support Django 1.9+

### PR DESCRIPTION
**Pull request by pombredanne**
@nowells would you consider pulling these fixes? They bring in support for 1.9+

### CODE REVIEW

**Comment by nowells** [comment]
@pombredanne thanks for doing this. I have invited you to be a collaborator, and will add you with collaborator access on PyPi as well. I have not actively maintained this (clearly) in a long while since my job changed (and I do not work with Django anymore 😦). Thank you for your contributions!

**Comment by pombredanne** [comment]
@nowells I merged this in. Thank you ++
You may want to be a collaborator too?

**Comment by pombredanne** [comment]
I did not waste time and pushed a new release 0.2.0 to Pypi ;)

**Comment by pombredanne** [comment]
https://pypi.python.org/pypi/django-pluggables/0.2.0 :P

**Comment by nowells** [comment]
> I did not waste time and pushed a new release 0.2.0 to Pypi ;)

Glad to hear it worked. Thanks for contributing to this and helping to maintain it. Cheers! I hope that my job/time will bring me back to Django and I can pick this back up.

**Pull request merged**
